region: us-west-2
arnStateMachine: 533588983801

# email para notificacion
alarmNotificationEmails:
  - Endpoint: jazmin@kranio.io
    Protocol: email

# Aquí deben ir todas tus arn role, vpc, deploymentbucket, etc.
