region: us-west-2
arnStateMachine: 533628681471 # este es un arn de ejemplo

# email para notificacion
alarmNotificationEmails:
  - Endpoint: jazmin@kranio.io
    Protocol: email

# Aquí deben ir todas tus arn role, vpc, deploymentbucket, etc.
